---
- name: Provisioning as learnt
  hosts: all
  become: yes
  tasks:
    - name: adding group
      ansible.builtin.group:
        name: faozil
        state: present
          
    - name: adding users
      user:
        name: "{{item.name}}"
        group: "{{item.group}}"
        shell: /bin/bash
      loop:
        - { name: 'faozil', group: 'faozil' }
        - { name: 'mum', group: 'root' }
        - { name: 'ridwan', group: 'faozil' }


    - name: Downloading ntp on centos
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - chrony
        - wget
        - httpd
        - zip
        - git
        - unzip

    - name: Downloading ntp on ubuntu
      apt:
        update_cache: yes
        name: "{{item}}"
        state: present
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - wget
        - apache2
        - zip
        - git
        - unzip

    - name: Starting ntp services
      service:
        name: "{{item}}"
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"
      loop:
        - chronyd
        - httpd

    - name: Starting ntp service on ubuntu
      service:
        name: "{{item}}"
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - apache2

