---
# handlers file for faozil
- name: restarting ntp service on CentOs
  service:
    name: "{{item}}"
    state: restarted
    enabled: yes
  when: ansible_distribution == "CentOS"
  loop:
     - chronyd
     - httpd

- name: restarting ntp service on ubuntu
  service:
    name: "{{item}}"
    state: restarted
    enabled: yes
  when: ansible_distribution == "Ubuntu"
  loop:
    - ntp
    - apache2
